In [2]:
import numpy as np

In [2]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
d=[5,5,5,5,5,5,5,5,5,5]
e=np.array(d)
e

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
even = np.arange(10,51,2)
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
id=np.eye(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
rn = np.random.rand()
rn

0.7862300020408166

In [24]:
r=np.random.rand(0,25)
r

array([], shape=(0, 25), dtype=float64)

In [3]:
random_numbers = np.random.normal(0, 1, 25)
print(random_numbers)

[-1.00356177 -0.53219517  0.29647463 -0.6224824   0.37439322 -0.89089636
  1.09121602  0.06424712 -0.32950115 -2.00871803  0.54336793 -2.37103434
  1.29067559 -0.24306996 -1.84828177  0.03467868  0.63628439 -0.31574526
 -1.17711846 -0.28964763 -0.34819414 -2.25175443  0.745818    0.03011623
  1.74258139]


In [4]:
sequence = np.arange(0.01, 1.01, 0.01)
result_array = sequence.reshape(10, 10)
print(result_array)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [5]:
ly = np.linspace(0, 1, 20)
print(ly)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [6]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
a=np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
a

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [10]:
a[1][3]

20

In [11]:
output_array = np.array([[2], [7], [12]])
print(output_array)

[[ 2]
 [ 7]
 [12]]


In [12]:
c=np.array([21,22,23,24,25])
c

array([21, 22, 23, 24, 25])

In [13]:
d=np.array([[16,17,18,19,20],[21,22,23,24,25]])
d

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat.sum()

325

In [15]:
dev = np.std(mat)
dev

7.211102550927978

In [16]:
col_sum = np.sum(mat,axis=0)
col_sum

array([55, 60, 65, 70, 75])